### ISSUE TITLE
2.8.1 Jshint

### ISSUE THREAD

**Issue by dotnetshadow** [RehanSaeed/ASP.NET-MVC-Boilerplate#46]
Hi there,

Everything seems to working well with v2.8.1 but if I choose the JSHint option I'm getting this error for the task runner:

```
cmd.exe /c gulp --tasks-simple
module.js:338
    throw err;
          ^
Error: Cannot find module 'jshint/src/cli'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\Programming\Projects\AspNetMvcBoilerPlate\test\test\node_modules\gulp-jshint\src\extract.js:1:79)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

It could be related to this:
http://stackoverflow.com/questions/33984558/gulp-error-cannot-find-module-jshint-src-cli

**Comment by dotnetshadow** [comment]
Actually I resolved the error I had to run this command:

```
npm install jshint gulp-jshint --save-dev
```

**Comment by RehanSaeed** [comment]
That's weird, it's been working for me. [This](https://github.com/spalger/gulp-jshint/issues/131) issue suggests that the JSHint package should be added or you can use the above approach which is a bit manual. I'll do some testing...

**Comment by RehanSaeed** [comment]
Just tried creating a new project on a separate machine and it seems fine. Is there something you are doing that's different?

**Comment by dotnetshadow** [comment]
I just tried it again with a new solution and I get the same problem, what npm version are you using?
I'm using v3.3.10

![capture1](https://cloud.githubusercontent.com/assets/296247/11671812/ee48b2aa-9e5e-11e5-89f3-73e3f3d6533b.PNG)

Just as a side note the the https issue I was getting with firefox is still there, I might open a new ticket for that one

**Comment by RehanSaeed** [comment]
Have you tried three instructions in the ReadMe. Delete the node_modules folder and do a npm clear cache?

**Comment by dotnetshadow** [comment]
I will give that a go, but the when I create a new solution there aren't any node_modules ? or do you mean from my users directory?

**Comment by RehanSaeed** [comment]
The node_modules folder gets created and populated on project creation when VS does a package restore. The trick is to shut down VS, delete this folder and also clear the npm package cache. The whole thing seems a bit flaky and I have seen packages get corrupted sometimes.

**Comment by RehanSaeed** [comment]
Any luck?

**Comment by dotnetshadow** [comment]
I need to test this still

**Comment by RehanSaeed** [comment]
Not sure what to say, I've tried on three machines multiple times and it's been ok. If you do find out what the problem is or if you find a solution, please post it here and I'll update the template.

**Comment by dotnetshadow** [comment]
I think I traced the error down to npm.
If I use npm 2.x then everything is fine
If I use npm 3.x where an error occurs

**Comment by RehanSaeed** [comment]
I also installed NPM 3 on one of the machines I tested on and it worked fine. Did you try downgrading `gulp-jshint`?

**Comment by dotnetshadow** [comment]
sorry how do u downgrade gulp-jshint? do you have the command handy?

**Comment by RehanSaeed** [comment]
Just lower the version number in package.json.

**Comment by RehanSaeed** [comment]
I'm closing this. Re-open if you find out what the problem was.
